version: '3'
services:
  web:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DEBUG: 1
    volumes:
      - .:/app
    ports:
     - "8000:8000"
    restart: on-failure