from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from sqlalchemy.orm import Session
from typing import List

from database.database_session import SessionLocal
from models.task import Task
from utils.auth import get_current_user

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

db: Session = SessionLocal()


class TaskService:
    def __init__(self, db):
        self.db = db

    def get_all_tasks(self, current_user: dict = Depends(get_current_user)) -> List[Task]:
        tasks = self.db.query(Task).filter(
            Task.user_id == current_user["sub"]).all()
        return tasks

    def get_task_by_id(self, task_id: int, current_user: dict = Depends(get_current_user)) -> Task:
        task = self.db.query(Task).filter(
            Task.id == task_id, Task.user_id == current_user["sub"]).first()
        if not task:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Task not found",
            )
        return task

    def create_task(self, task_data: Task, current_user: dict = Depends(get_current_user)) -> Task:
        new_task = Task(**task_data.dict(), user_id=current_user["sub"])
        self.db.add(new_task)
        self.db.commit()
        # Refresh to get the ID generated by the database
        self.db.refresh(new_task)
        return new_task

    def update_task(self, task_id: int, task_data: Task, current_user: dict = Depends(get_current_user)) -> Task:
        task = self.get_task_by_id(task_id, current_user)
        if not task:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Task not found",
            )
        updated_data = task_data.dict(exclude_unset=True)
        for field, value in updated_data.items():
            setattr(task, field, value)
        self.db.commit()
        self.db.refresh(task)
        return task

    def delete_task(self, task_id: int, current_user: dict = Depends(get_current_user)) -> bool:
        task = self.get_task_by_id(task_id, current_user)
        if task:
            self.db.delete(task)
            self.db.commit()
            return True
        return False
